services:
  webapp:
    env_file: # remove hardcoded config and put it in .env file
      - .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"  # required to manually create random postgres password
    build:
      target: runner # multi-stage build feature
      tags:
        - "${DEV_BUILD_REMOTE_TAG}"

    restart: always
    ports:
      - ::80  # ephemeral port feature
      - ::443 # ephemeral port feature
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - joomlavolume:/app/public

  db:
    env_file: # remove hardcoded config and put it in .env file
      - .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"  # required to manually create random postgres password
      PGDATA: /var/lib/postgresql/data/pgdata
    image: "${BASE_DB_IMAGE}"
    restart: always
    volumes:
      - dbvolume:/var/lib/postgresql/data

volumes:
  joomlavolume:
  dbvolume:
