services:
  webapp:
    env_file: # remove hardcoded config and put it in .env file
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  # required to manually create random mysql password
    build:
      target: runner # multi-stage build feature
      tags:
        - "${DEV_BUILD_REMOTE_TAG}"

    restart: always
    ports:
      - ::80  # ephemeral port feature
      - ::443 # ephemeral port feature
    volumes:
      - joomlavolume:/app/public
    depends_on:
      - db

  db:
    env_file: # remove hardcoded config and put it in .env file
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"  # required to manually create random mysql password
    image: "${BASE_DB_IMAGE}"
    restart: always
    volumes:
      - dbvolume:/var/lib/mysql

volumes:
  joomlavolume:
  dbvolume:
