version: '3.1'

services:

  joomla:
    build: .
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: exampleuser
      JOOMLA_DB_PASSWORD: examplepass
      JOOMLA_DB_NAME: exampledb
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    volumes:
      - joomla:/app/public

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  joomla:
  db:
